'use strict';
define('service/EMOJIS',['at_app'], function(app) {
    app.lazy.service('EMOJIS',
        function() {
            return [{
                "phrase": /\[草泥马\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/shenshou_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/shenshou_thumb.gif",
                "value": "[草泥马]",
                "picid": ""
            }, {
                "phrase": /\[神马\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/horse2_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/horse2_thumb.gif",
                "value": "[神马]",
                "picid": ""
            }, {
                "phrase": /\[浮云\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/fuyun_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/fuyun_thumb.gif",
                "value": "[浮云]",
                "picid": ""
            }, {
                "phrase": /\[给力\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/geili_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/geili_thumb.gif",
                "value": "[给力]",
                "picid": ""
            }, {
                "phrase": /\[围观\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/wg_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/wg_thumb.gif",
                "value": "[围观]",
                "picid": ""
            }, {
                "phrase": /\[威武\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/vw_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/vw_thumb.gif",
                "value": "[威武]",
                "picid": ""
            }, {
                "phrase": /\[熊猫\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/panda_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/panda_thumb.gif",
                "value": "[熊猫]",
                "picid": ""
            }, {
                "phrase": /\[兔子\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/rabbit_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/rabbit_thumb.gif",
                "value": "[兔子]",
                "picid": ""
            }, {
                "phrase": /\[奥特曼\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/otm_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/otm_thumb.gif",
                "value": "[奥特曼]",
                "picid": ""
            }, {
                "phrase": /\[囧\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/j_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/j_thumb.gif",
                "value": "[囧]",
                "picid": ""
            }, {
                "phrase": /\[互粉\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/hufen_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/hufen_thumb.gif",
                "value": "[互粉]",
                "picid": ""
            }, {
                "phrase": /\[礼物\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/liwu_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/liwu_thumb.gif",
                "value": "[礼物]",
                "picid": ""
            }, {
                "phrase": /\[呵呵\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/smilea_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/smilea_thumb.gif",
                "value": "[呵呵]",
                "picid": ""
            }, {
                "phrase": /\[嘻嘻\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/tootha_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/tootha_thumb.gif",
                "value": "[嘻嘻]",
                "picid": ""
            }, {
                "phrase": /\[哈哈\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/laugh.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/laugh.gif",
                "value": "[哈哈]",
                "picid": ""
            }, {
                "phrase": /\[可爱\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/tza_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/tza_thumb.gif",
                "value": "[可爱]",
                "picid": ""
            }, {
                "phrase": /\[可怜\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/kl_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/kl_thumb.gif",
                "value": "[可怜]",
                "picid": ""
            }, {
                "phrase": /\[挖鼻屎\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/kbsa_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/kbsa_thumb.gif",
                "value": "[挖鼻屎]",
                "picid": ""
            }, {
                "phrase": /\[吃惊\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/cj_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/cj_thumb.gif",
                "value": "[吃惊]",
                "picid": ""
            }, {
                "phrase": /\[害羞\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/shamea_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/shamea_thumb.gif",
                "value": "[害羞]",
                "picid": ""
            }, {
                "phrase": /\[挤眼\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/zy_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/zy_thumb.gif",
                "value": "[挤眼]",
                "picid": ""
            }, {
                "phrase": /\[闭嘴\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/bz_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/bz_thumb.gif",
                "value": "[闭嘴]",
                "picid": ""
            }, {
                "phrase": /\[鄙视\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/bs2_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/bs2_thumb.gif",
                "value": "[鄙视]",
                "picid": ""
            }, {
                "phrase": /\[爱你\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/lovea_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/lovea_thumb.gif",
                "value": "[爱你]",
                "picid": ""
            }, {
                "phrase": /\[泪\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/sada_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/sada_thumb.gif",
                "value": "[泪]",
                "picid": ""
            }, {
                "phrase": /\[偷笑\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/heia_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/heia_thumb.gif",
                "value": "[偷笑]",
                "picid": ""
            }, {
                "phrase": /\[亲亲\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/qq_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/qq_thumb.gif",
                "value": "[亲亲]",
                "picid": ""
            }, {
                "phrase": /\[生病\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/sb_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/sb_thumb.gif",
                "value": "[生病]",
                "picid": ""
            }, {
                "phrase": /\[太开心\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/mb_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/mb_thumb.gif",
                "value": "[太开心]",
                "picid": ""
            }, {
                "phrase": /\[懒得理你\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/ldln_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/ldln_thumb.gif",
                "value": "[懒得理你]",
                "picid": ""
            }, {
                "phrase": /\[右哼哼\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/yhh_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/yhh_thumb.gif",
                "value": "[右哼哼]",
                "picid": ""
            }, {
                "phrase": /\[左哼哼\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/zhh_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/zhh_thumb.gif",
                "value": "[左哼哼]",
                "picid": ""
            }, {
                "phrase": /\[嘘\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/x_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/x_thumb.gif",
                "value": "[嘘]",
                "picid": ""
            }, {
                "phrase": /\[衰\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/cry.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/cry.gif",
                "value": "[衰]",
                "picid": ""
            }, {
                "phrase": /\[委屈\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/wq_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/wq_thumb.gif",
                "value": "[委屈]",
                "picid": ""
            }, {
                "phrase": /\[吐\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/t_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/t_thumb.gif",
                "value": "[吐]",
                "picid": ""
            }, {
                "phrase": /\[打哈欠\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/k_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/k_thumb.gif",
                "value": "[打哈欠]",
                "picid": ""
            }, {
                "phrase": /\[抱抱\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/bba_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/bba_thumb.gif",
                "value": "[抱抱]",
                "picid": ""
            }, {
                "phrase": /\[怒\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/angrya_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/angrya_thumb.gif",
                "value": "[怒]",
                "picid": ""
            }, {
                "phrase": /\[疑问\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/yw_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/yw_thumb.gif",
                "value": "[疑问]",
                "picid": ""
            }, {
                "phrase": /\[馋嘴\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/cza_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/cza_thumb.gif",
                "value": "[馋嘴]",
                "picid": ""
            }, {
                "phrase": /\[拜拜\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/88_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/88_thumb.gif",
                "value": "[拜拜]",
                "picid": ""
            }, {
                "phrase": /\[思考\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/sk_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/sk_thumb.gif",
                "value": "[思考]",
                "picid": ""
            }, {
                "phrase": /\[汗\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/sweata_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/sweata_thumb.gif",
                "value": "[汗]",
                "picid": ""
            }, {
                "phrase": /\[困\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/sleepya_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/sleepya_thumb.gif",
                "value": "[困]",
                "picid": ""
            }, {
                "phrase": /\[睡觉\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/sleepa_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/sleepa_thumb.gif",
                "value": "[睡觉]",
                "picid": ""
            }, {
                "phrase": /\[钱\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/money_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/money_thumb.gif",
                "value": "[钱]",
                "picid": ""
            }, {
                "phrase": /\[失望\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/sw_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/sw_thumb.gif",
                "value": "[失望]",
                "picid": ""
            }, {
                "phrase": /\[酷\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/cool_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/cool_thumb.gif",
                "value": "[酷]",
                "picid": ""
            }, {
                "phrase": /\[花心\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/hsa_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/hsa_thumb.gif",
                "value": "[花心]",
                "picid": ""
            }, {
                "phrase": /\[哼\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/hatea_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/hatea_thumb.gif",
                "value": "[哼]",
                "picid": ""
            }, {
                "phrase": /\[鼓掌\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/gza_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/gza_thumb.gif",
                "value": "[鼓掌]",
                "picid": ""
            }, {
                "phrase": /\[晕\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/dizzya_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/dizzya_thumb.gif",
                "value": "[晕]",
                "picid": ""
            }, {
                "phrase": /\[悲伤\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/bs_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/bs_thumb.gif",
                "value": "[悲伤]",
                "picid": ""
            }, {
                "phrase": /\[抓狂\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/crazya_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/crazya_thumb.gif",
                "value": "[抓狂]",
                "picid": ""
            }, {
                "phrase": /\[黑线\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/h_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/h_thumb.gif",
                "value": "[黑线]",
                "picid": ""
            }, {
                "phrase": /\[阴险\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/yx_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/yx_thumb.gif",
                "value": "[阴险]",
                "picid": ""
            }, {
                "phrase": /\[怒骂\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/nm_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/nm_thumb.gif",
                "value": "[怒骂]",
                "picid": ""
            }, {
                "phrase": /\[心\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/hearta_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/hearta_thumb.gif",
                "value": "[心]",
                "picid": ""
            }, {
                "phrase": /\[伤心\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/unheart.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/unheart.gif",
                "value": "[伤心]",
                "picid": ""
            }, {
                "phrase": /\[猪头\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/pig.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/pig.gif",
                "value": "[猪头]",
                "picid": ""
            }, {
                "phrase": /\[ok\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/ok_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/ok_thumb.gif",
                "value": "[ok]",
                "picid": ""
            }, {
                "phrase": /\[耶\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/ye_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/ye_thumb.gif",
                "value": "[耶]",
                "picid": ""
            }, {
                "phrase": /\[good\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/good_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/good_thumb.gif",
                "value": "[good]",
                "picid": ""
            }, {
                "phrase": /\[不要\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/no_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/no_thumb.gif",
                "value": "[不要]",
                "picid": ""
            }, {
                "phrase": /\[赞\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/z2_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/z2_thumb.gif",
                "value": "[赞]",
                "picid": ""
            }, {
                "phrase": /\[来\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/come_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/come_thumb.gif",
                "value": "[来]",
                "picid": ""
            }, {
                "phrase": /\[弱\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/sad_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/sad_thumb.gif",
                "value": "[弱]",
                "picid": ""
            }, {
                "phrase": /\[蜡烛\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/lazu_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/lazu_thumb.gif",
                "value": "[蜡烛]",
                "picid": ""
            }, {
                "phrase": /\[钟\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/clock_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/clock_thumb.gif",
                "value": "[钟]",
                "picid": ""
            }, {
                "phrase": /\[话筒\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/m_org.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/m_thumb.gif",
                "value": "[话筒]",
                "picid": ""
            }, {
                "phrase": /\[蛋糕\]/g,
                "type": "face",
                "url": "/atmanlib/asset/images/emojis/cake.gif",
                "hot": false,
                "common": true,
                "category": "",
                "icon": "images/emojis/cake.gif",
                "value": "[蛋糕]",
                "picid": ""
            }];
        });
})